language: php

php:
  - 7.3
  - 7.4
  - 8.0

script:
  - composer run test
  - composer run check

before_script:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer update
  - mkdir -p build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls
